name: 'yqtb'

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  yqtb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: QingQiz/AoxiangRobot
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install --upgrade -r requirements.txt
      - name: main
        shell: bash {0}
        run: |
          echo ${{ secrets.AOXIANG_PASSWORD }} > ./password
          retry=0
          until [ "$retry" -ge 10 ]
          do
            ./aoxiangRobot -u ${{ secrets.AOXIANG_USERNAME }} -p ./password yqtb \
              -p "${{ secrets.YQTB_PROVINCE }}" \
              -c "${{ secrets.YQTB_CITY }}" \
              -l ${{ secrets.YQTB_LOCATION }} && break
            ((retry++))
            echo -e "\033[0;31mCheckin failed, retry ${retry}\033[0m"
            sleep 1m
          done
