name: 'yqtb'

on:
  schedule:
    - cron: '12,43 1-8 * * *'
  workflow_dispatch:

jobs:
  yqtb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: QingQiz/AoxiangRobot
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install --upgrade -r requirements.txt
      - name: main
        run: |
          echo ${{ secrets.AOXIANG_PASSWORD }} > ./password
          ./aoxiangRobot -u ${{ secrets.AOXIANG_USERNAME }} -p ./password yqtb \
            -p "${{ secrets.YQTB_PROVINCE }}" \
            -c "${{ secrets.YQTB_CITY }}" \
            -l ${{ secrets.YQTB_LOCATION }}
